-- جدول مستقل گزارش نبردها
create table if not exists public.battle_reports (
  id bigint generated by default as identity primary key,
  battle_number bigint generated by default as identity unique,
  battle_id text not null unique,
  attacker_name text not null default 'مهاجم',
  defender_name text not null default 'مدافع',
  winner text not null default '',
  end_reason text not null default '',
  report jsonb not null default '[]'::jsonb,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists battle_reports_created_at_idx
  on public.battle_reports (created_at desc);
